// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    EditorMarkdown: typeof import('./src/components/editor/markdown.vue')['default']
    EditorMonaco: typeof import('./src/components/editor/monaco.vue')['default']
    'EditorPreview.ce': typeof import('./src/components/editor/preview.ce.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/footer.vue')['default']
    LayoutHelp: typeof import('./src/components/layout/help.vue')['default']
    LayoutSider: typeof import('./src/components/layout/sider.vue')['default']
    NResult: typeof import('naive-ui')['NResult']
    PostEditor: typeof import('./src/components/post/editor.vue')['default']
    PostInfo: typeof import('./src/components/post/info.vue')['default']
    PostList: typeof import('./src/components/post/list.vue')['default']
    PostTabs: typeof import('./src/components/post/tabs.vue')['default']
    PostToc: typeof import('./src/components/post/toc.vue')['default']
    PostTocItem: typeof import('./src/components/post/tocItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowModal: typeof import('./src/components/ShowModal.vue')['default']
    SplitPane: typeof import('./src/components/SplitPane.vue')['default']
    StateTag: typeof import('./src/components/StateTag.vue')['default']
    StatusBarMenu: typeof import('./src/components/StatusBarMenu.vue')['default']
  }
}
