export default <GlobalConfig>{
	layout: {
		layoutSiderWidth: "54px",
		layoutFooterBar: "22px",
		editorAsideWidth: "280px",
		isShowLayoutSider: true,
		isShowLayoutEditorAside: true,
		isShowMarkdownEditor: true,
		isShowMarkdownPrew: true,
	},
	theme: "light",
	language: "zh_cn",
	preStyle: "",
	preTag: "",
	preClass: "",
	editorLightTheme: "vs",
	editorDartTheme: "vs-dark",
	editorOption: {
		lineNumbers: "off",
		minimap: {
			enabled: true,
			renderCharacters: false,
		},
		fontSize: 14,
		fontFamily: undefined,
		wordWrap: "on",
		mouseWheelZoom: true,
	},
	autoSave: 0,
	autoRender: 200,
	hideFrontMatter: false,
	imgStorageType: "Local",
	imgStorageDir: "source/images/",
	pictureBed: "",
};
